export type ScraperConfig = {
    id: string
    name: string
    endpoint: string
    backendId?: string
    columns: { key: string; label: string }[]
    description: string
}

export const SCRAPER_CONFIGS: Record<string, ScraperConfig> = {
    "eauctions": {
        id: "eauctions",
        name: "E-Auctions India",
        endpoint: "/api/scrape/eauctions",
        backendId: "eauctionsindia",
        description: "Scrape e-auction listings.",
        columns: [
            { key: "url", label: "URL" },
            { key: "bank", label: "Bank" },
            { key: "property_type", label: "Property Type" },
            { key: "reserve_price", label: "Reserve Price" },
            { key: "emd", label: "EMD" },
            { key: "auction_date", label: "Auction Date" },
            { key: "branch", label: "Branch" },
            { key: "contact", label: "Contact" },
            { key: "city", label: "City" },
            { key: "area", label: "Area" },
            { key: "description", label: "Description" },
        ],
    },
    "speakers": {
        id: "speakers",
        name: "Speakers Scraper",
        endpoint: "/api/scrape/speakers",
        backendId: "speakers",
        description: "Find event speakers and profiles.",
        columns: [
            { key: "name", label: "Name" },
            { key: "designation", label: "Designation" },
            { key: "organization", label: "Organization" },
            { key: "location", label: "Location" },
            { key: "about", label: "About" },
            { key: "linkedin", label: "LinkedIn" },
            { key: "experience", label: "Experience" },
            { key: "imageurl", label: "Image URL" },
            { key: "profileurl", label: "Profile URL" },
        ],
    },
    "gitex": {
        id: "gitex",
        name: "Gitex Exhibitors",
        endpoint: "/api/scrape/gitex",
        backendId: "gitex_exhibitors",
        description: "Scrape Gitex exhibitor list.",
        columns: [
            { key: "company_name", label: "Company_Name" },
            { key: "designation", label: "Designation" },
            { key: "sectors", label: "Sectors" },
            { key: "facebook", label: "Facebook" },
            { key: "twitter", label: "Twitter" },
            { key: "linkedin", label: "LinkedIn" },
            { key: "instagram", label: "Instagram" },
            { key: "youtube", label: "Youtube" },
            { key: "profile_url", label: "Profile URL" },
        ],
    },
    "google-maps": {
        id: "google-maps",
        name: "Google Maps",
        endpoint: "/api/scrape/gmaps",
        backendId: "gmap_scraper",
        description: "Extract business information from Google Maps.",
        columns: [
            { key: "name", label: "Name" },
            { key: "rating", label: "Rating" },
            { key: "address", label: "Address" },
            { key: "phone", label: "Phone" },
            { key: "website", label: "Website" },
            { key: "email", label: "Email ID" },
            { key: "url", label: "URL" },
        ],
    },
    "twitter": {
        id: "twitter",
        name: "Twitter Scraper",
        endpoint: "/api/scrape/twitter",
        backendId: "twitter",
        description: "Scrape tweets, profiles, and engagement metrics.",
        columns: [
            { key: "username", label: "Username" },
            { key: "post_text", label: "Post Text" },
            { key: "likes", label: "Likes" },
            { key: "replies", label: "Replies" },
            { key: "shares", label: "Shares" },
            { key: "date", label: "Date" },
            { key: "url", label: "URL" },
        ],
    },
    "youtube": {
        id: "youtube",
        name: "YouTube Scraper",
        endpoint: "/api/scrape/youtube",
        backendId: "youtube",
        description: "Scrape video details and channel info.",
        columns: [
            { key: "topic", label: "Topic" },
            { key: "video_id", label: "Video ID" },
            { key: "title", label: "Title" },
            { key: "channel_name", label: "Channel Name" },
            { key: "channel_id", label: "Channel ID" },
            { key: "views", label: "Views" },
            { key: "likes", label: "Likes" },
            { key: "comments", label: "Comments" },
            { key: "published_date", label: "Published Date" },
            { key: "description", label: "Description" },
            { key: "url", label: "URL" },
        ],
    },
    "instagram": {
        id: "instagram",
        name: "Instagram Scraper",
        endpoint: "/api/scrape/instagram",
        backendId: "instagram",
        description: "Scrape Instagram profiles and posts.",
        columns: [
            { key: "username", label: "Username" },
            { key: "post_text", label: "Post Text" },
            { key: "likes", label: "Likes" },
            { key: "replies", label: "Replies" },
            { key: "shares", label: "Shares" },
            { key: "date", label: "Date" },
            { key: "url", label: "URL" },
        ],
    },
    "instagram-articles": {
        id: "instagram-articles",
        name: "Instagram Articles",
        endpoint: "/api/scrape/instagram-articles",
        backendId: "instagram_articles",
        description: "Extract articles or long-form content from Instagram.",
        columns: [
            { key: "platform", label: "Platform" },
            { key: "topic", label: "Topic" },
            { key: "username", label: "Username" },
            { key: "post_text", label: "Post Text" },
            { key: "likes", label: "Likes" },
            { key: "comments", label: "Comments" },
            { key: "shares", label: "Shares" },
            { key: "date", label: "Date" },
            { key: "url", label: "URL" },
        ],
    },
    "linkedin-articles": {
        id: "linkedin-articles",
        name: "LinkedIn Articles",
        endpoint: "/api/scrape/linkedin-articles",
        backendId: "linkedin_articles",
        description: "Scrape articles from LinkedIn based on keywords.",
        columns: [
            { key: "platform", label: "Platform" },
            { key: "topic", label: "Topic" },
            { key: "author", label: "Author" },
            { key: "post_text", label: "Post Text" },
            { key: "likes", label: "Likes" },
            { key: "comments", label: "Comments" },
            { key: "shares", label: "Shares" },
            { key: "date", label: "Date" },
            { key: "post_url", label: "Post URL" },
        ],
    },
    "linkedin-jobs": {
        id: "linkedin-jobs",
        name: "LinkedIn Jobs",
        endpoint: "/api/scrape/linkedin-jobs",
        backendId: "linkedin_jobs",
        description: "Find job listings on LinkedIn.",
        columns: [
            { key: "job_title", label: "Job Title" },
            { key: "company_name", label: "Company Name" },
            { key: "post_time", label: "Post Date" },
            { key: "applications_count", label: "Applications" },
            { key: "job_location", label: "Location" },
            { key: "job_description", label: "Job Description" },
            { key: "salary", label: "Salary" },
            { key: "seniority_level", label: "Seniority Level" },
            { key: "employment_type", label: "Employment Type" },
            { key: "job_function", label: "Job Function" },
            { key: "industries", label: "Industries" },
            { key: "job_url", label: "Job URL" },
        ],
    },
    "opentable": {
        id: "opentable",
        name: "OpenTable",
        endpoint: "/api/scrape/opentable",
        backendId: "opentable_restaurant",
        description: "Extract restaurant data from OpenTable.",
        columns: [
            { key: "restaurant_name", label: "Restaurant Name" },
            { key: "cuisine", label: "Cuisine" },
            { key: "rating", label: "Rating" },
            { key: "reviews_count", label: "Reviews" },
            { key: "price", label: "Price" },
            { key: "location", label: "Location" },
            { key: "phone", label: "Phone" },
            { key: "description", label: "Description" },
            { key: "menu_link", label: "Menu Link" },
            { key: "source_url", label: "Source URL" },
        ],
    },
    "restaurants": {
        id: "restaurants",
        name: "Restaurant Scraper",
        endpoint: "/api/scrape/restaurants",
        backendId: "restaurant_scraper",
        description: "Generic restaurant scraper for various platforms.",
        columns: [
            { key: "city", label: "City" },
            { key: "restaurant_name", label: "Restaurant Name" },
            { key: "phone", label: "Phone" },
            { key: "website", label: "Website" },
            { key: "email", label: "Email" },
            { key: "reviews", label: "Reviews" },
            { key: "rating", label: "Rating" },
            { key: "address", label: "Address" },
        ],
    },
    "reddit": {
        id: "reddit",
        name: "Reddit Scraper",
        endpoint: "/api/scrape/reddit",
        backendId: "reddit",
        description: "Gather posts and comments from Subreddits.",
        columns: [
            { key: "platform", label: "Platform" },
            { key: "topic", label: "Topic" },
            { key: "title", label: "Title" },
            { key: "subreddit", label: "Subreddit" },
            { key: "user", label: "User" },
            { key: "upvotes", label: "Upvotes" },
            { key: "replies", label: "Replies" },
            { key: "url", label: "URL" },
        ],
    },
    "reddit-threads": {
        id: "reddit-threads",
        name: "Reddit Thread Scraper",
        endpoint: "/api/scrape/reddit-threads",
        backendId: "reddit_threads",
        description: "Extract detailed thread discussions.",
        columns: [
            { key: "platform", label: "Platform" },
            { key: "topic", label: "Topic" },
            { key: "thread_url", label: "Thread URL" },
            { key: "post_title", label: "Post Title" },
            { key: "subreddit", label: "Subreddit" },
            { key: "post_author", label: "Post Author" },
            { key: "comment_author", label: "Comment Author" },
            { key: "comment_text", label: "Comment Text" },
            { key: "comment_upvotes", label: "Comment Upvotes" },
        ],
    },
    "london-scraper": {
        id: "london-scraper",
        name: "London Speakers",
        endpoint: "/api/scrape/london-scraper",
        backendId: "london-scraper",
        description: "Scrape speakers from London-based bureaus.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "Speaking Sessions", label: "Sessions" },
            { key: "LinkedIn", label: "LinkedIn" },
            { key: "Source URL", label: "Source URL" },
        ],
    },
    "india-scraper": {
        id: "india-scraper",
        name: "India Speakers",
        endpoint: "/api/scrape/india-scraper",
        backendId: "india-scraper",
        description: "Scrape Indian event speakers.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "Speaking Sessions", label: "Sessions" },
            { key: "LinkedIn", label: "LinkedIn" },
            { key: "Source URL", label: "Source URL" },
        ],
    },
    "gartner-scraper": {
        id: "gartner-scraper",
        name: "Gartner CFO Finance",
        endpoint: "/api/scrape/gartner-scraper",
        backendId: "gartner-scraper",
        description: "Scrape Gartner CFO Finance conference speakers.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Speaker Bio", label: "Bio" },
            { key: "Speaker Topics", label: "Topics" },
            { key: "Sessions", label: "Sessions" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "bharat-2025": {
        id: "bharat-2025",
        name: "Bharat 2025",
        endpoint: "/api/scrape/bharat-2025",
        backendId: "bharat-2025",
        description: "Scrape Bharat 2025 event data.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Company", label: "Company" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "bharat-2023": {
        id: "bharat-2023",
        name: "Bharat 2023",
        endpoint: "/api/scrape/bharat-2023",
        backendId: "bharat-2023",
        description: "Scrape Bharat 2023 archive data.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Company", label: "Company" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "bharat-fintech": {
        id: "bharat-fintech",
        name: "Bharat Fintech",
        endpoint: "/api/scrape/bharat-fintech",
        backendId: "bharat-fintech",
        description: "Scrape Bharat Fintech Summit speakers.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Company", label: "Company" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "fof-scraper": {
        id: "fof-scraper",
        name: "Future of Finance",
        endpoint: "/api/scrape/fof-scraper",
        backendId: "fof-scraper",
        description: "Scrape Future of Finance speakers.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "isb-scraper": {
        id: "isb-scraper",
        name: "Indian Speaker Bureau",
        endpoint: "/api/scrape/isb-scraper",
        backendId: "isb-scraper",
        description: "Scrape Indian Speaker Bureau profiles.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "lsb-scraper": {
        id: "lsb-scraper",
        name: "London Speaker Bureau",
        endpoint: "/api/scrape/lsb-scraper",
        backendId: "lsb-scraper",
        description: "Scrape London Speaker Bureau profiles.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "nexgen-scraper": {
        id: "nexgen-scraper",
        name: "NexGen Banking",
        endpoint: "/api/scrape/nexgen-scraper",
        backendId: "nexgen-scraper",
        description: "Scrape NexGen Banking conference details.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "leading-authorities": {
        id: "leading-authorities",
        name: "Leading Authorities",
        endpoint: "/api/scrape/leading-authorities",
        backendId: "leading-authorities",
        description: "Scrape Leading Authorities bureau speakers.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "LinkedIn", label: "LinkedIn" },
        ],
    },
    "uk-scraper": {
        id: "uk-scraper",
        name: "UK Speakers",
        endpoint: "/api/scrape/uk-scraper",
        backendId: "uk-scraper",
        description: "Scrape speakers from UK regions.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "Speaking Sessions", label: "Sessions" },
            { key: "Contact Number", label: "Phone" },
            { key: "LinkedIn", label: "LinkedIn" },
            { key: "Source URL", label: "Source URL" },
        ],
    },
    "us-scraper": {
        id: "us-scraper",
        name: "US Speakers",
        endpoint: "/api/scrape/us-scraper",
        backendId: "us-scraper",
        description: "Scrape speakers from US regions.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "Speaking Sessions", label: "Sessions" },
            { key: "LinkedIn", label: "LinkedIn" },
            { key: "Source URL", label: "Source URL" },
        ],
    },
    "europe-scraper": {
        id: "europe-scraper",
        name: "Europe Speakers",
        endpoint: "/api/scrape/europe-scraper",
        backendId: "europe-scraper",
        description: "Scrape speakers from European regions.",
        columns: [
            { key: "Name", label: "Name" },
            { key: "Role/Designation", label: "Role" },
            { key: "Bio", label: "Bio" },
            { key: "Speaking Sessions", label: "Sessions" },
            { key: "LinkedIn", label: "LinkedIn" },
            { key: "Source URL", label: "Source URL" },
        ],
    },
}
